server:
  port: 8081
  servlet:
    context-path: /api

poc:
  workflow-engine-url: http://localhost:8080
  start-workflow-url: /engine-rest/process-definition/key/{0}/start
  hello-workflow-key: HelloWorkflow
  history-process-url: /engine-rest/history/process-instance?processInstanceBusinessKey={0}
  history-variable-url: /engine-rest/history/variable-instance?processInstanceId={0}&variableName=payload
